spring:
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      username: admin
      password: test
      host: localhost
      port: 27017
      database: user-service
      authentication-database: admin

server:
  port: 8892